import { createHash } from "node:crypto";
import { createReadStream } from "node:fs";
import { lstat, readdir, realpath, rmdir, unlink } from "node:fs/promises";
import { basename, dirname, isAbsolute, join, relative, resolve, sep } from "node:path";

export interface TemporaryArtifact { path: string; size: number; sha256: string }
export interface TemporaryCleanupResult {
  removed_count: number;
  retained_count: number;
  retained_paths: string[];
  retained_truncated: boolean;
}

function inside(workspace: string, path: string): boolean {
  if (!isAbsolute(path) || resolve(path) !== path) return false;
  const rel = relative(workspace, path);
  return Boolean(rel && rel !== ".." && !rel.startsWith(`..${sep}`) && !isAbsolute(rel));
}

/** Hash a regular file within the canonical task workspace, without following symlinks. */
export async function hashOwnedTemporaryFile(path: string, workspace: string, signal?: AbortSignal): Promise<{ size: number; sha256: string } | undefined> {
  try {
    if (!inside(workspace, path)) return undefined;
    const before = await lstat(path);
    if (!before.isFile() || before.isSymbolicLink() || await realpath(path) !== path) return undefined;
    const hash = createHash("sha256");
    for await (const chunk of createReadStream(path, { signal })) hash.update(chunk as Buffer);
    const after = await lstat(path);
    if (before.ino !== after.ino || before.size !== after.size || before.mtimeMs !== after.mtimeMs) return undefined;
    return { size: after.size, sha256: hash.digest("hex") };
  } catch { return undefined; }
}

async function retainedEntries(workspace: string): Promise<Pick<TemporaryCleanupResult, "retained_count" | "retained_paths" | "retained_truncated">> {
  const paths: string[] = [];
  let count = 0;
  let truncated = false;
  const pending = [workspace];
  while (pending.length) {
    const directory = pending.pop()!;
    let entries;
    try { entries = await readdir(directory, { withFileTypes: true }); }
    catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") continue; throw error; }
    if (!entries.length && directory !== workspace) {
      count++;
      if (paths.length < 10) paths.push(relative(workspace, directory));
    }
    for (const entry of entries) {
      const path = join(directory, entry.name);
      if (entry.isDirectory() && !entry.isSymbolicLink()) pending.push(path);
      else {
        count++;
        if (paths.length < 10) paths.push(relative(workspace, path));
      }
      if (count + pending.length > 10_000) { truncated = true; break; }
    }
    if (truncated) break;
  }
  return { retained_count: count, retained_paths: paths, retained_truncated: truncated };
}

/** Delete only exact task-generated bytes; unknown or changed entries remain untouched. */
export async function cleanupTemporaryFiles(workspace: string, expectedWorkspace: string, artifacts: TemporaryArtifact[]): Promise<TemporaryCleanupResult> {
  if (!isAbsolute(workspace) || resolve(workspace) !== expectedWorkspace || basename(dirname(expectedWorkspace)) !== ".babel-content" || !/^job_[a-f0-9-]{36}$/.test(basename(expectedWorkspace))) throw new Error("TEMP_WORKSPACE_SCOPE_MISMATCH");
  const parent = dirname(expectedWorkspace);
  for (const path of [parent, expectedWorkspace]) {
    const info = await lstat(path);
    if (!info.isDirectory() || info.isSymbolicLink() || await realpath(path) !== path) throw new Error("TEMP_WORKSPACE_SCOPE_MISMATCH");
  }
  let removed = 0;
  const candidateDirs = new Set<string>();
  for (const artifact of artifacts) {
    if (!Number.isSafeInteger(artifact.size) || artifact.size < 0 || !/^[a-f0-9]{64}$/.test(artifact.sha256)) continue;
    const actual = await hashOwnedTemporaryFile(artifact.path, expectedWorkspace);
    if (!actual || actual.size !== artifact.size || actual.sha256 !== artifact.sha256) continue;
    try { await unlink(artifact.path); candidateDirs.add(dirname(artifact.path)); removed++; }
    catch { /* A changed or protected file remains. */ }
  }
  for (const dir of [...candidateDirs, expectedWorkspace].sort((a, b) => b.length - a.length)) {
    let current = dir;
    while (current === expectedWorkspace || current.startsWith(`${expectedWorkspace}${sep}`)) {
      try { await rmdir(current); } catch { break; }
      if (current === expectedWorkspace) break;
      current = dirname(current);
    }
  }
  return { removed_count: removed, ...await retainedEntries(expectedWorkspace) };
}
